### ISSUE TITLE
Get the database error "groot get -d arg-annot"

### ISSUE THREAD

**Issue by lancetxiao** [will-rowe/groot#21] opened 2019-09-09 03:45 UTC
Hi， Thanks for this great tool！
 In **source activate grootTutorial**
When I  "groot get -d arg-annot"
It Shows the error message
"downloading the pre-clustered arg-annot database...
unpacking...
could not unpack the tarball
arg-annot.90/: illegal file path"
or
"downloading the pre-clustered arg-annot database...
could not download the tarball
Get https://raw.githubusercontent.com/will-rowe/groot/master/db/clustered-ARG-databases/arg-annot.90.tar: dial tcp 151.101.228.133:443: i/o timeout"

When just use the "conda install groot & groot get -d arg-annot" no Error shows, 
Could Anyone  Help me, Thanks a lot?

**Comment by will-rowe** [comment] 2019-09-09 08:57
Thanks for filing the issue! This is a bug which was fixed in a previous version (caused by a dependency changing their API). You've found this because I forgot to update the GROOT version number in the tutorial!

I will update the tutorial to use the following cmd for the conda env:

```
conda create -n grootTutorial -c bioconda parallel sra-tools==2.8 fastqc==0.11.7 bbmap==37.90 multiqc groot==0.8.5 seqkit==0.7.2 samtools==1.4 metacherchant==0.1.0
```

**Comment by lancetxiao** [comment] 2019-09-09 09:42
Thanks for your help.

**Comment by will-rowe** [comment] 2019-09-09 10:05
No worries! Have merged the changes into the master branch now, so you should be set!

**Closed by will-rowe** 2019-09-09 10:05 UTC
